Document: libutil
Title: Debian libutil Manual
Author: <insert document author here>
Abstract: This manual describes what libutil is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libutil/libutil.sgml.gz

Format: postscript
Files: /usr/share/doc/libutil/libutil.ps.gz

Format: text
Files: /usr/share/doc/libutil/libutil.text.gz

Format: HTML
Index: /usr/share/doc/libutil/html/index.html
Files: /usr/share/doc/libutil/html/*.html
